on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: nooose/custom-slack-message@master
      with:
        who-to-greet: 'Mona the Octocat'