on:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: test message
      uses: nooose/custom-slack-message@master
      with:
        SLACK_WEBHOOK: http://naver.com
        TYPE: PR

    - name: echo pr info
      run: |
        echo [INFO] PR_NUMBER : ${{ github.event.number }}

